name: cdn-bump-version
description: Uploads version file to CDN
inputs:
  cf-bucket:
    description: Name of the S3 bucket
    required: true
  version-list:
    description: 'List of versions, separated by newlines'
    required: true
  release-channel:
    description: 'Release channel that describes this upload'
    required: true

runs:
  using: composite
  steps:

    - name: Upload version file
      shell: bash
      run: |
        mkdir upload
        echo "${{ inputs.version-list }}" >> upload/version-${{ inputs.release-channel }}.txt
        rclone copy upload cdn:${{ inputs.cf-bucket }}/
