name: 'Question'
description: "Is there a feature you'd really like to see? Request it here."
title: '[Question] '
labels: ['type: question']
projects: ['OpenShock/3']

body:

  - type: markdown
    attributes:
      value: |
        # Question

  - type: textarea
    id: question
    attributes:
      label: 'Ask your question!'
      description: "Don't hold back."
      placeholder: |
        How do I..?
        Is it possible to..?
        Are you planning to..?
    validations:
      required: true
