on:
  push:
    branches:
      - master
      - feature/multi-board-ci
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize]

name: ci-master

env:
  SHOCKLINK_API_DOMAIN: api.shocklink.net
  SHOCKLINK_FW_VERSION: master-${{ github.sha }}

jobs:

  # Copied verbatim from https://docs.platformio.org/en/stable/integration/ci/github-actions.html
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        chip: [esp32, esp32-s3, esp32-c3]
      
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/platforms
            ~/.platformio/packages
            ~/.platformio/cache
          key: ${{ runner.os }}-arch

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run -e ${{ matrix.chip }}

      - name: Upload internal artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firmware_${{ matrix.chip }}.bin
          path: .pio/build/*/firmware.bin
          retention-days: 1