on:
  push:
    branches:
      - master
      - feature/captive-portal-ci
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize]

name: ci-master

env:
  NODE_VERSION: 16
  PYTHON_VERSION: 3.9
  SHOCKLINK_API_DOMAIN: api.shocklink.net
  SHOCKLINK_FW_VERSION: master-${{ github.sha }}

jobs:

  build-captive-portal:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            WebUI
          path: .

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ./WebUI/package-lock.json

      - name: Install dependencies
        working-directory: ./WebUI
        run: npm ci

      - name: Build
        working-directory: ./WebUI
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: captive-portal
          path: WebUI/build/*
          retention-days: 1
          if-no-files-found: error
  
  build-filesystem:
    runs-on: ubuntu-latest
    needs: build-captive-portal
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: |
            ~/.platformio/platforms
            ~/.platformio/packages
            ~/.platformio/cache
          key: ${{ runner.os }}-arch

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"
      
      - uses: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Download built captive portal
        uses: actions/download-artifact@v3
        with:
          name: captive-portal
          path: WebUI/build/

      - name: Build filesystem
        run: pio run --target buildfs
      
      - name: Upload internal filesystem artifact
        uses: actions/upload-artifact@v3
        with:
          name: filesystem
          path: .pio/build/*/littlefs.bin
          retention-days: 1
          if-no-files-found: error

  build-firmware:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: |
            ~/.platformio/platforms
            ~/.platformio/packages
            ~/.platformio/cache
          key: ${{ runner.os }}-arch

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build firmware
        run: pio run

      - name: Upload internal firmware binaries
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: .pio/build/*/*.bin
          retention-days: 1
          if-no-files-found: error

  merge-images:
    runs-on: ubuntu-latest
    needs: [build-filesystem, build-firmware]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: "pip"
      
      - name: Install esptool
        run: pip install esptool

      - name: Merge flash image
        run: |
          esptool merge_bin \
            -o merged.bin \
            --chip esp32 \
            --flash_mode dio \
            --flash_freq 40m \
            --flash_size 4MB \
            0x1000 ./bootloader.bin \
            0x8000 ./partitions.bin \
            0x10000 ./firmware.bin \
            0x310000 ./littlefs.bin

      - name: Upload merged flashable image
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: merged.bin
          retention-days: 1
          if-no-files-found: error
