on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-*'

name: ci-tag
run-name: "tag-build: ${{ github.ref_name }}"

jobs:

  # Build all targets. This step also outputs the strategy matrix containing the names
  # of each board that is being built for.
  build:
    uses: ./.github/workflows/ci-build.yml

  # create-dummy-artifact:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Make artifact
  #       run: |
  #         echo "artifact 1" >> OpenShock.Example1.bin
  #         echo "artifact 2" >> OpenShock.Example2.bin

  #     - name: Upload artifacts
  #       uses: actions/upload-artifact@v3
  #       with:
  #         path: OpenShock.Example1.bin
  #         name: OpenShock_Example1

  #     - name: Upload artifacts
  #       uses: actions/upload-artifact@v3
  #       with:
  #         path: OpenShock.Example2.bin
  #         name: OpenShock_Example2
