on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-*'

name: ci-tag
run-name: "ci-tag: ${{ github.ref_name }}"

env:
  NODE_VERSION: 16
  PYTHON_VERSION: 3.12
  OPENSHOCK_API_DOMAIN: api.shocklink.net
  # OPENSHOCK_FW_VERSION:
  #   - If this is a tag push, we can use ref_name to get the tag name.
  #   - If this is branch "master" or "develop", we use "0.0.0-master" or "0.0.0-develop" respectively.
  #   - All other scenarios we use "0.0.0-unknown", as we cannot guarantee SemVer compliance by accepting any branch name. So this is the safe option.
  OPENSHOCK_FW_VERSION: ${{ (startsWith(github.ref, 'refs/tags/') && github.ref_name) || (contains(fromJSON('["master","develop"]'), github.ref_name) && format('0.0.0-{0}', github.ref_name)) || '0.0.0-unknown' }}
  OPENSHOCK_FW_COMMIT: ${{ github.sha }}

jobs:

  # Read platformio.ini and extract all specific targets. See the referenced file for more info.
  get-targets:
    uses: ./.github/workflows/get-targets.yml

  build-captive-portal:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            WebUI

      - uses: ./.github/actions/build-captive-portal
        with:
          node-version: ${{ env.NODE_VERSION }}
          skip-checkout: true

  build-filesystem:
    runs-on: ubuntu-latest
    needs: build-captive-portal

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-filesystem
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          skip-checkout: true

  build-firmware:
    runs-on: ubuntu-latest
    needs: get-targets
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.get-targets.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/build-firmware
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          board: ${{ matrix.board }}
          skip-checkout: true

  merge-images:
    runs-on: ubuntu-latest
    needs: [get-targets, build-filesystem, build-firmware]
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.get-targets.outputs.matrix )}}

    steps:
      - uses: actions/checkout@v4
        with:
          path: .
          sparse-checkout: |
            .github
            scripts
            boards
            chips

      - name: Merge images
        uses: ./.github/actions/merge-images
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          board: ${{ matrix.board }}
          skip-checkout: true

  release:
    runs-on: ubuntu-latest
    needs: [merge-images]

    steps:
      - name: Download release notes
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            RELEASE.md

      - name: Download release artifacts
        uses: actions/download-artifact@v3

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./**/OpenShock_*.bin\
          tag: ${{ github.ref_name }}
          prerelease: ${{ contains(github.ref_name, '-') }}
          artifactErrorsFailBuild: true
          bodyFile: README.md
