on:
  push:
    branches:
      - feature/captive-portal-ci
    tags:
      - 'v**'

name: ci-tag

env:
  SHOCKLINK_API_DOMAIN: api.shocklink.net
  SHOCKLINK_FW_VERSION: ${{ github.ref_name }}

jobs:

  build:
    uses: ./.github/workflows/ci-build.yml

  publish:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download release notes
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            RELEASE.md

      # Note: This step is NOT in fact `actions/download-artifact`. The reason is that since we
      # invoked the build workflow as a sub-workflow, we cannot directly access its artifacts.
      # This alternative implementation enables us to do it regardless.
      - name: Download build artifacts
        uses: dawidd6/action-download-artifact@v2.28.0
        with:
          name: merged-firmware.bin
          name_is_regexp: false
          run_id: ${{ github.event.workflow_run.id }}
          search_artifacts: true

      # This step reads a file from repo and use it for body of the release
      # This works on any self-hosted runner OS
      - name: Read RELEASE.md
        id: read_release
        shell: bash
        run: |
          r=$(cat RELEASE.md)                               # <--- Read release.md (Provide correct path as per your repo)
          r="${r//'%'/'%25'}"                               # Multiline escape sequences for %
          r="${r//$'\n'/'%0A'}"                             # Multiline escape sequences for '\n'
          r="${r//$'\r'/'%0D'}"                             # Multiline escape sequences for '\r'
          echo "RELEASE_BODY=$r" >> $GITHUB_OUTPUT          # <--- Set environment variable

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: merged-firmware.bin
          asset_name: ShockLink.bin
          tag: ${{ github.ref }}
          body: |
            ${{ steps.read_release.outputs.RELEASE_BODY }}
