on:
  workflow_run:
    workflows: ["ci-tag"]
    types:
      - completed

jobs:

  # Download all artifacts from the previous workflow.
  publish:
    runs-on: ubuntu-latest

    steps:

      # Download all final artifacts from the competed ci-tag workflow
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2.28.0
        with:
          name: OpenShock_.*
          name_is_regexp: true
          run_id: ${{ github.event.workflow_run.id }}
          workflow_conclusion: success
          search_artifacts: false

      - name: Test
        run: |
          echo "${{ github.event.workflow_run.head_branch }}"

      # Upload artifacts to release.
      # - name: Upload artifact to release
      #   uses: svenstaro/upload-release-action@v2
      #   with:
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     file: OpenShock.*.bin
      #     file_glob: true
      #     tag: ${{ github.ref }}
      #     prerelease: ${{ contains(github.ref_name, '-') }}
